### ISSUE TITLE
Attach source location

### ISSUE THREAD

**Issue by roberth** [cachix/katip-raven#5]

**Comment by domenkozar** [comment]
This will be possible only in GHC 8.10 as dwarf finally becomes useful there. So another 6 months or so.

**Comment by roberth** [comment]
That's for stack traces. What about `HasCallstack`-based location that katip should be providing?
Having a single source location is nicer, especially if you set it up so that any convenience functions pass on the location of their caller. I'm not sure that can be done with dwarf stacks and include a whole stack trace every time seems costly.
